GRANT SELECT ON SYS.USER$ TO MESS;
GRANT DBA TO MESS;
ALTER USER MESS DEFAULT ROLE ALL;
GRANT UNLIMITED TABLESPACE TO MESS;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO MESS;
GRANT SELECT ON SYS.USER$ TO MESS;
GRANT SELECT ON SYS.V_$MYSTAT TO MESS;
GRANT SELECT ON SYS.V_$SESSION TO MESS;
ALTER USER MESS  GRANT CONNECT THROUGH ORDS_PUBLIC_USER;
/
