/* Formatted on 6/4/2023 10:52:27 PM (QP5 v5.227.12220.39754) */
ALTER TABLE CASH_SUB
ADD (MES_ID NUMBER);

ALTER TABLE MEAL_COUNT
ADD (MES_ID NUMBER);

ALTER TABLE MEAL_PERIOD
ADD (MES_ID NUMBER);

ALTER TABLE SHOP_EXP
ADD (MES_ID NUMBER);

ALTER TABLE SHOP_EXP_D
ADD (MES_ID NUMBER);

ALTER TABLE M_MEMBER
ADD (MES_ID NUMBER);