CREATE TABLE MEAL_COUNT
(
  ID         NUMBER(20),
  M_ID       NUMBER,
  MEAL_DATE  DATE
);
/



CREATE TABLE MEAL_PERIOD
(
  ID         NUMBER,
  MEAL_ID    NUMBER,
  BREAKFAST  NUMBER(1),
  LUNCH      NUMBER(1),
  DINNER     NUMBER(1)
);




CREATE TABLE M_MEMBER
(
  ID          NUMBER,
  FULL_NAME   VARCHAR2(100 BYTE),
  PHONE       VARCHAR2(30 BYTE),
  EMAIL       VARCHAR2(30 BYTE),
  PICTURE     BLOB,
  ADDRESS     VARCHAR2(200 BYTE),
  NID         VARCHAR2(20 BYTE),
  PROFESSION  VARCHAR2(50 BYTE)
);
/


CREATE TABLE SHOP_EXP
(
  ID          NUMBER,
  SHOP_DATE   DATE,
  SHOPPER_ID  NUMBER,
  COST_AMT    NUMBER(10,2),
  OTHER_COST  NUMBER(10,2)
);
/


CREATE TABLE CASH_SUB
(
  ID           NUMBER,
  M_MEMBER_ID  NUMBER,
  CASH_AMT     NUMBER(10,2),
  CASH_SUB     DATE
);
/

ALTER TABLE MEAL_COUNT ADD (
  PRIMARY KEY
  (ID));

ALTER TABLE MEAL_PERIOD ADD (
  PRIMARY KEY
  (ID));

ALTER TABLE M_MEMBER ADD (
  PRIMARY KEY
  (ID));

ALTER TABLE SHOP_EXP ADD (
  PRIMARY KEY
  (ID));

ALTER TABLE CASH_SUB ADD (  
  PRIMARY KEY
  (ID));

ALTER TABLE CASH_SUB ADD (
  CONSTRAINT CASH_SUB_R01 
  FOREIGN KEY (M_MEMBER_ID) 
  REFERENCES M_MEMBER (ID)
  ENABLE VALIDATE);
