ALTER TABLE MESMILL.ITEM_MASTER
 DROP PRIMARY KEY CASCADE;

DROP TABLE MESMILL.ITEM_MASTER CASCADE CONSTRAINTS;

CREATE TABLE MESMILL.ITEM_MASTER
(
  ID         NUMBER,
  ITEM_NAME  VARCHAR2(50 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE MESMILL.MEAL_COUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MESMILL.MEAL_COUNT CASCADE CONSTRAINTS;

CREATE TABLE MESMILL.MEAL_COUNT
(
  ID         NUMBER(20),
  M_ID       NUMBER,
  MEAL_DATE  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE MESMILL.MEAL_PERIOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE MESMILL.MEAL_PERIOD CASCADE CONSTRAINTS;

CREATE TABLE MESMILL.MEAL_PERIOD
(
  ID         NUMBER,
  MEAL_ID    NUMBER,
  BREAKFAST  NUMBER(1),
  LUNCH      NUMBER(1),
  DINNER     NUMBER(1)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE MESMILL.MESS_NAME
 DROP PRIMARY KEY CASCADE;

DROP TABLE MESMILL.MESS_NAME CASCADE CONSTRAINTS;

CREATE TABLE MESMILL.MESS_NAME
(
  ID         NUMBER,
  MESS_NAME  VARCHAR2(50 BYTE),
  ADDRESS    VARCHAR2(200 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE MESMILL.M_MEMBER
 DROP PRIMARY KEY CASCADE;

DROP TABLE MESMILL.M_MEMBER CASCADE CONSTRAINTS;

CREATE TABLE MESMILL.M_MEMBER
(
  ID          NUMBER,
  FULL_NAME   VARCHAR2(100 BYTE),
  PHONE       VARCHAR2(30 BYTE),
  EMAIL       VARCHAR2(30 BYTE),
  PICTURE     BLOB,
  ADDRESS     VARCHAR2(200 BYTE),
  NID         VARCHAR2(20 BYTE),
  PROFESSION  VARCHAR2(50 BYTE)
)
LOB (PICTURE) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          104K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE MESMILL.SHOP_EXP
 DROP PRIMARY KEY CASCADE;

DROP TABLE MESMILL.SHOP_EXP CASCADE CONSTRAINTS;

CREATE TABLE MESMILL.SHOP_EXP
(
  ID          NUMBER,
  SHOP_DATE   DATE,
  SHOPPER_ID  NUMBER,
  COST_AMT    NUMBER(10,2),
  OTHER_COST  NUMBER(10,2)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE MESMILL.SHOP_EXP_D CASCADE CONSTRAINTS;

CREATE TABLE MESMILL.SHOP_EXP_D
(
  ID       NUMBER,
  EXP_ID   NUMBER,
  ITEM_ID  NUMBER,
  UNIT     NUMBER,
  QTY      NUMBER,
  PRICE    NUMBER(10,2)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index MESMILL.SYS_C0029514.
--  The object is created when the parent object is created.

--  There is no statement for index MESMILL.SYS_C0029515.
--  The object is created when the parent object is created.

--  There is no statement for index MESMILL.SYS_C0029516.
--  The object is created when the parent object is created.

--  There is no statement for index MESMILL.SYS_C0029518.
--  The object is created when the parent object is created.

--  There is no statement for index MESMILL.SYS_C0029525.
--  The object is created when the parent object is created.

--  There is no statement for index MESMILL.SYS_C0029526.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER MESMILL.trg_items_pk
   BEFORE INSERT OR UPDATE
   ON MESMILL.ITEM_MASTER
   FOR EACH ROW
BEGIN
   IF :new.id IS NULL
   THEN
      SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM item_master;
   END IF;
END trg_items_pk;
/


CREATE OR REPLACE TRIGGER MESMILL.trg_mess_name_pk
   BEFORE INSERT OR UPDATE
   ON MESMILL.MESS_NAME
   FOR EACH ROW
BEGIN
   IF :new.id IS NULL
   THEN
      SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM mess_name;
   END IF;
END trg_mess_name_pk;
/


CREATE OR REPLACE TRIGGER MESMILL.trg_shop_exp_pk
   BEFORE INSERT OR UPDATE
   ON MESMILL.SHOP_EXP
   FOR EACH ROW
BEGIN
   IF :new.id IS NULL
   THEN
      SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM SHOP_EXP;
   END IF;
END trg_shop_exp_pk;
/


CREATE OR REPLACE TRIGGER MESMILL.trg_shop_exp_d_pk
   BEFORE INSERT OR UPDATE
   ON MESMILL.SHOP_EXP_D
   FOR EACH ROW
BEGIN
   IF :new.id IS NULL
   THEN
      SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM SHOP_EXP_D;
   END IF;
END trg_shop_exp_d_pk;
/


ALTER TABLE MESMILL.CASH_SUB
 DROP PRIMARY KEY CASCADE;

DROP TABLE MESMILL.CASH_SUB CASCADE CONSTRAINTS;

CREATE TABLE MESMILL.CASH_SUB
(
  ID           NUMBER,
  M_MEMBER_ID  NUMBER,
  CASH_AMT     NUMBER(10,2),
  CASH_SUB     DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index MESMILL.SYS_C0029517.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER MESMILL.trg_cash_sub_pk
   BEFORE INSERT OR UPDATE
   ON MESMILL.CASH_SUB
   FOR EACH ROW
BEGIN
   IF :new.id IS NULL
   THEN
      SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM cash_sub;
   END IF;
END trg_cash_sub_pk;
/


ALTER TABLE MESMILL.ITEM_MASTER ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE MESMILL.MEAL_COUNT ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE MESMILL.MEAL_PERIOD ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE MESMILL.MESS_NAME ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE MESMILL.M_MEMBER ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE MESMILL.SHOP_EXP ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE MESMILL.CASH_SUB ADD (
  CONSTRAINT CASH_SUB_C01
  CHECK (m_member_id is not null)
  ENABLE VALIDATE,
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE MESMILL.SHOP_EXP_D ADD (
  CONSTRAINT SHOP_EXP_D_R01 
  FOREIGN KEY (EXP_ID) 
  REFERENCES MESMILL.SHOP_EXP (ID)
  ENABLE VALIDATE);

ALTER TABLE MESMILL.CASH_SUB ADD (
  CONSTRAINT CASH_SUB_R01 
  FOREIGN KEY (M_MEMBER_ID) 
  REFERENCES MESMILL.M_MEMBER (ID)
  ENABLE VALIDATE);
